#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================
# 12_export_snv_axas_style.sh
#
# Export target ProbeSet genotypes from the NEW run-specific Step2
# AxiomGT1.calls.txt. It does not read/copy template CHP genotype files.
#
# Primary validation target is the genotype matrix (base_call), because
# AxAS batch-level SNP performance columns require a run-specific
# SelectedAdditionalDataColumns file generated by AxAS SNP-QC processing.
# ============================================================

CONFIG="${1:?run_config.sh 필요}"
# shellcheck disable=SC1090
source "$CONFIG"

SNV_STEP2_DIR="${SNV_STEP2_DIR:-${OUT}/11_snv_step2}"
SNV_EXPORT_DIR="${SNV_EXPORT_DIR:-${OUT}/12_snv_export}"
SNV_CALLS_FILE="${SNV_CALLS_FILE:-${SNV_STEP2_DIR}/AxiomGT1.calls.txt}"
SNV_ADDITIONAL_SNP_INFORMATION_FILE="${SNV_ADDITIONAL_SNP_INFORMATION_FILE:-}"

mkdir -p "$SNV_EXPORT_DIR"

if [ ! -s "$SNV_CALLS_FILE" ]; then
  echo "[ERROR] Step2 calls file not found: $SNV_CALLS_FILE"
  exit 1
fi
if [ ! -s "$PROBESET_LIST" ]; then
  echo "[ERROR] ProbeSet list not found: $PROBESET_LIST"
  exit 1
fi
if [ ! -s "$ANNOTATION_FILE" ]; then
  echo "[ERROR] Annotation DB not found: $ANNOTATION_FILE"
  exit 1
fi

OUT_TXT="${SNV_EXPORT_DIR}/${RUN_NAME}_snv_axas_style.txt"
MATRIX_TXT="${SNV_EXPORT_DIR}/${RUN_NAME}_snv_genotype_matrix.tsv"
EXCLUDED_TXT="${SNV_EXPORT_DIR}/probesets_excluded_from_step2.txt"
MANIFEST="${SNV_EXPORT_DIR}/snv_export_manifest.tsv"
UNKNOWN_CALLS="${SNV_EXPORT_DIR}/unknown_call_codes.tsv"

python3 - \
  "$SNV_CALLS_FILE" \
  "$PROBESET_LIST" \
  "$ANNOTATION_FILE" \
  "$SNV_ADDITIONAL_SNP_INFORMATION_FILE" \
  "$OUT_TXT" \
  "$MATRIX_TXT" \
  "$EXCLUDED_TXT" \
  "$UNKNOWN_CALLS" \
  "$SNV_STEP2_DIR" <<'PY'
from __future__ import print_function
import csv
import os
import re
import sqlite3
import sys

calls_file, target_file, annotation_db, additional_file, out_txt, matrix_txt, excluded_txt, unknown_txt, batch_folder = sys.argv[1:]

annotation_columns = [
    "Affy_SNP_ID", "Chr_id", "Start", "Stop", "Strand", "dbSNP_RS_ID",
    "dbSNP_Loctype", "In_Hapmap", "Strand_Vs_dbSNP", "Probe_Count",
    "Cytoband", "ChrX_PAR", "Flank", "Allele_A", "Allele_B",
    "Ref_Allele", "Alt_Allele", "Associated_Gene", "Genetic_Map",
    "Microsatellite", "Heterozygous_Allele_Frequencies",
    "Allele_Frequency_Count", "Allele_Frequencies", "Minor_Allele",
    "Minor_Allele_Frequency", "OMIM", "Biomedical", "Annotation_Notes",
    "Ordered_Alleles", "Allele_Count", "extended_rsid", "acmg_gene",
    "clinvar_variantid", "clinvar_mim", "clinvar_omim_phenotype",
    "clinvar_traits", "clinvar_gene", "clinvar_clin_sig",
    "clinvar_hgvs_c", "clinvar_hgvs_g", "clinvar_reviewstatus",
    "nhgri_traits", "mpcr_region", "module_name", "category",
    "trivial_name", "cn_region"
]

def norm(s):
    return ''.join(ch.lower() for ch in str(s) if ch.isalnum())

def read_targets(path):
    out=[]; seen=set()
    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            line=line.strip().replace('\r','')
            if not line or line.startswith('#'):
                continue
            v=re.split(r'[\t, ]+', line)[0].strip().strip('"')
            if norm(v) in {'probesetid','id'}:
                continue
            if v and v not in seen:
                seen.add(v); out.append(v)
    return out

def parse_calls(path, wanted):
    code_map={}
    sample_names=None
    selected={}
    wanted_set=set(wanted)
    callcode_re=re.compile(r'^#%+call-code-\d+=(.*)$')
    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            line=line.rstrip('\r\n')
            m=callcode_re.match(line)
            if m:
                rhs=m.group(1)
                p=rhs.split(':')
                if len(p) >= 2:
                    try:
                        code_map[int(p[1])] = p[0]
                    except ValueError:
                        pass
                continue
            if line.startswith('probeset_id\t'):
                sample_names=line.split('\t')[1:]
                continue
            if sample_names is None or not line or line.startswith('#'):
                continue
            psid=line.split('\t',1)[0]
            if psid not in wanted_set:
                continue
            parts=line.split('\t')
            vals=parts[1:]
            if len(vals) < len(sample_names):
                vals += ['']*(len(sample_names)-len(vals))
            selected[psid]=vals[:len(sample_names)]
    if sample_names is None:
        raise RuntimeError('probeset_id header not found in AxiomGT1.calls.txt')
    if not code_map:
        code_map={-4:'OTV_1',-3:'NoCall_1',-2:'OTV',-1:'NoCall',0:'AA',1:'AB',2:'BB',3:'ZeroCN',4:'A',5:'B',6:'C',7:'AC',8:'BC',9:'CC'}
    return sample_names, code_map, selected

def qident(s):
    return '"'+str(s).replace('"','""')+'"'

def load_annotations(db_path, wanted):
    conn=sqlite3.connect(db_path)
    cur=conn.cursor()
    tables=[r[0] for r in cur.execute("SELECT name FROM sqlite_master WHERE type='table'")]
    table=idcol=None; cols=[]
    for t in tables:
        info=list(cur.execute('PRAGMA table_info(%s)' % qident(t)))
        c=[x[1] for x in info]
        for x in c:
            if norm(x)=='probesetid':
                table=t; idcol=x; cols=c; break
        if table: break
    if not table:
        conn.close(); raise RuntimeError('Annotation table with ProbeSet_ID not found')
    lookup={norm(c):c for c in cols}
    actual={out:lookup.get(norm(out)) for out in annotation_columns}
    select_actual=[]
    for c in actual.values():
        if c and c not in select_actual: select_actual.append(c)
    result={}
    wanted=list(wanted)
    for i in range(0,len(wanted),400):
        chunk=wanted[i:i+400]
        sql='SELECT %s FROM %s WHERE %s IN (%s)' % (
            ','.join(qident(x) for x in [idcol]+select_actual),
            qident(table),qident(idcol),','.join('?' for _ in chunk))
        for row in cur.execute(sql,chunk):
            raw={c:('' if v is None else str(v)) for c,v in zip(select_actual,row[1:])}
            result[str(row[0])]={out:(raw.get(ac,'') if ac else '') for out,ac in actual.items()}
    conn.close()
    return result

def allele_map(ann):
    ordered=(ann.get('Ordered_Alleles') or '').strip()
    vals=[]
    if ordered:
        vals=[x.strip() for x in re.split(r'\s*//\s*|\s*\|\s*',ordered) if x.strip()]
    # Some annotation records have an unhelpful Ordered_Alleles value; A/B are authoritative fallbacks.
    if len(vals) < 2:
        vals=[]
        for k in ('Allele_A','Allele_B'):
            v=(ann.get(k) or '').strip()
            if v: vals.append(v)
    letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    return {letters[i]:v for i,v in enumerate(vals[:len(letters)])}

def decode(raw, code_map, ann, unknown_records, psid, sample):
    raw=raw.strip()
    if raw=='': return '---'
    try:
        code=int(raw)
        label=code_map.get(code)
    except ValueError:
        label=raw
        code=None
    if label is None:
        unknown_records.append((psid,sample,raw,'unmapped_numeric_code'))
        return '---'
    upper=label.upper()
    if upper in {'NOCALL','NOCALL_1','OTV','OTV_1'}:
        return '---'
    if upper in {'ZEROCN','CN0','ZEROCOPYNUMBER','ZERO_COPY_NUMBER'}:
        # Current positive target set does not contain a CN0 call; keep missing semantics for base_call export.
        return '---'
    amap=allele_map(ann)
    # Axiom call labels can be AA/AB/BB, haploid A/B, or multiallelic AC/BC/CC/... .
    if label and all(ch.isalpha() and ch.upper() in amap for ch in label):
        bases=[amap[ch.upper()] for ch in label]
        return bases[0] if len(bases)==1 else '/'.join(bases)
    unknown_records.append((psid,sample,raw,label))
    return '---'

def read_additional(path):
    if not path or not os.path.isfile(path) or os.path.getsize(path)==0:
        return [], {}
    with open(path,encoding='utf-8',errors='replace',newline='') as f:
        first=f.readline(); delim='\t' if '\t' in first else ','; f.seek(0)
        rdr=csv.reader(f,delimiter=delim)
        header=None
        for row in rdr:
            if row and not row[0].startswith('#'):
                header=row; break
        if not header: return [],{}
        ididx=0
        for i,h in enumerate(header):
            if norm(h)=='probesetid': ididx=i; break
        cols=[h for i,h in enumerate(header) if i!=ididx]
        data={}
        for row in rdr:
            if not row or len(row)<=ididx: continue
            ps=row[ididx]
            vals=[(row[i] if i<len(row) else '') for i in range(len(header)) if i!=ididx]
            data[ps]=vals
        return cols,data

targets=read_targets(target_file)
samples,code_map,raw_calls=parse_calls(calls_file,targets)
ann=load_annotations(annotation_db,targets)
additional_cols,additional=read_additional(additional_file)

present=[x for x in targets if x in raw_calls]
excluded=[x for x in targets if x not in raw_calls]
unknown=[]
decoded={}
for psid in present:
    a=ann.get(psid,{})
    decoded[psid]=[decode(v,code_map,a,unknown,psid,s) for v,s in zip(raw_calls[psid],samples)]

with open(excluded_txt,'w',encoding='utf-8') as f:
    f.write('probeset_id\n')
    for x in excluded: f.write(x+'\n')
with open(unknown_txt,'w',encoding='utf-8') as f:
    f.write('probeset_id\tsample\traw_code\tparsed_label\n')
    for row in unknown: f.write('\t'.join(map(str,row))+'\n')

sample_out=[s+'_call_code' if not s.endswith('_call_code') else s for s in samples]

# Simple call matrix: best file for one-to-one validation against AxAS call columns.
with open(matrix_txt,'w',encoding='utf-8',newline='') as f:
    w=csv.writer(f,delimiter='\t',lineterminator='\n')
    w.writerow(['probeset_id']+sample_out)
    for psid in present:
        w.writerow([psid]+decoded[psid])

# AxAS-like TXT: genotype base_call values are intended to match AxAS; path metadata may differ.
# Batch-level SNP-QC columns are appended ONLY if a run-specific additional file is explicitly supplied.
with open(out_txt,'w',encoding='utf-8',newline='') as f:
    f.write('##batch-folder=%s\n' % batch_folder)
    f.write('##annotation-file=%s\n' % annotation_db)
    f.write('##export-txt-file=%s\n' % out_txt)
    f.write('##snp-count=%d\n' % len(present))
    f.write('##samples-per-snp=%d\n' % len(samples))
    w=csv.writer(f,delimiter='\t',lineterminator='\n')
    w.writerow(['probeset_id']+sample_out+annotation_columns+additional_cols)
    for psid in present:
        a=ann.get(psid,{})
        add=additional.get(psid,['']*len(additional_cols))
        if len(add)<len(additional_cols): add=add+['']*(len(additional_cols)-len(add))
        w.writerow([psid]+decoded[psid]+[a.get(c,'') for c in annotation_columns]+add[:len(additional_cols)])

print('[INFO] Step2 samples           =',len(samples))
print('[INFO] requested probesets     =',len(targets))
print('[INFO] exported probesets      =',len(present))
print('[INFO] excluded from Step2     =',len(excluded))
print('[INFO] unknown call-code cells =',len(unknown))
print('[INFO] AxAS-style TXT          =',out_txt)
print('[INFO] genotype matrix         =',matrix_txt)
PY

SAMPLE_COUNT="$(awk 'NR==1{print NF-1}' "$MATRIX_TXT")"
SNP_COUNT="$(awk 'END{print NR-1}' "$MATRIX_TXT")"
EXCLUDED_COUNT="$(awk 'END{print NR-1}' "$EXCLUDED_TXT")"
UNKNOWN_COUNT="$(awk 'END{print NR-1}' "$UNKNOWN_CALLS")"

{
  printf "key\tvalue\n"
  printf "step2_calls\t%s\n" "$SNV_CALLS_FILE"
  printf "probeset_list\t%s\n" "$PROBESET_LIST"
  printf "annotation_file\t%s\n" "$ANNOTATION_FILE"
  printf "axas_style_output\t%s\n" "$OUT_TXT"
  printf "genotype_matrix\t%s\n" "$MATRIX_TXT"
  printf "exported_snp_count\t%s\n" "$SNP_COUNT"
  printf "sample_count\t%s\n" "$SAMPLE_COUNT"
  printf "excluded_probeset_count\t%s\n" "$EXCLUDED_COUNT"
  printf "unknown_call_code_cell_count\t%s\n" "$UNKNOWN_COUNT"
  printf "additional_snp_information_file\t%s\n" "$SNV_ADDITIONAL_SNP_INFORMATION_FILE"
} > "$MANIFEST"

if [ "$UNKNOWN_COUNT" -ne 0 ]; then
  echo "[ERROR] Unknown Step2 call codes were found."
  echo "[CHECK] $UNKNOWN_CALLS"
  exit 1
fi

echo "============================================================"
echo "[DONE] SNV AxAS-style export"
echo "[SNP_COUNT]      $SNP_COUNT"
echo "[SAMPLE_COUNT]   $SAMPLE_COUNT"
echo "[EXCLUDED]       $EXCLUDED_COUNT"
echo "[OUTPUT]         $OUT_TXT"
echo "[MATRIX]         $MATRIX_TXT"
echo "============================================================"
